version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s [%(levelname)-8s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  detailed:
    format: "%(asctime)s [%(levelname)-8s] [%(filename)s:%(lineno)d] %(name)s %(message)s "
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: log/application.log
    encoding: utf-8
    maxBytes: 10485760
    backupCount: 5
  file_error:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: detailed
    filename: log/error.log
    encoding: utf-8
    maxBytes: 10485760
    backupCount: 5
  root_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout
loggers:
  app:
    level: DEBUG
    handlers: [console, file, file_error]
    propagate: no
  # app.test_module:
  #   level: DEBUG
  #   handlers: [file]
  #   propagate: no
root:
  level: DEBUG
  handlers: [root_console, file]